# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
