# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_headline_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='newspaper',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
    ]
